version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python app/db.py &&
             uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/github_prs_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/github_prs_test
    depends_on:
      - web-db

  web-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=github_prs_dev

volumes:
  data:
